services:
  db:
    image: postgres:16-alpine
    container_name: bank-db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: bank
    ports:
      - 5432:5432

